services:
  frontend:
    build:
      context: .
      dockerfile: project_template_web.dockerfile
    restart: always
    container_name: frontend
    env_file: ".env"
    ports:
      - "8001:8001"